////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2008 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 1.50Release
// Tag = $Name: AKW1_500 $
////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;

import java.util.ArrayList;

public class Factory {
   static public Mesg createMesg(Mesg mesg) {
      switch (mesg.getNum()) {       
         case MesgNum.FILE_ID:
            return new FileIdMesg(mesg);       
         case MesgNum.FILE_CREATOR:
            return new FileCreatorMesg(mesg);       
         case MesgNum.PAD:
            return new PadMesg(mesg);       
         case MesgNum.SOFTWARE:
            return new SoftwareMesg(mesg);       
         case MesgNum.CAPABILITIES:
            return new CapabilitiesMesg(mesg);       
         case MesgNum.FILE_CAPABILITIES:
            return new FileCapabilitiesMesg(mesg);       
         case MesgNum.MESG_CAPABILITIES:
            return new MesgCapabilitiesMesg(mesg);       
         case MesgNum.FIELD_CAPABILITIES:
            return new FieldCapabilitiesMesg(mesg);       
         case MesgNum.DEVICE_SETTINGS:
            return new DeviceSettingsMesg(mesg);       
         case MesgNum.USER_PROFILE:
            return new UserProfileMesg(mesg);       
         case MesgNum.HRM_PROFILE:
            return new HrmProfileMesg(mesg);       
         case MesgNum.SDM_PROFILE:
            return new SdmProfileMesg(mesg);       
         case MesgNum.BIKE_PROFILE:
            return new BikeProfileMesg(mesg);       
         case MesgNum.ZONES_TARGET:
            return new ZonesTargetMesg(mesg);       
         case MesgNum.SPORT:
            return new SportMesg(mesg);       
         case MesgNum.HR_ZONE:
            return new HrZoneMesg(mesg);       
         case MesgNum.POWER_ZONE:
            return new PowerZoneMesg(mesg);       
         case MesgNum.MET_ZONE:
            return new MetZoneMesg(mesg);       
         case MesgNum.GOAL:
            return new GoalMesg(mesg);       
         case MesgNum.ACTIVITY:
            return new ActivityMesg(mesg);       
         case MesgNum.SESSION:
            return new SessionMesg(mesg);       
         case MesgNum.LAP:
            return new LapMesg(mesg);       
         case MesgNum.RECORD:
            return new RecordMesg(mesg);       
         case MesgNum.EVENT:
            return new EventMesg(mesg);       
         case MesgNum.DEVICE_INFO:
            return new DeviceInfoMesg(mesg);       
         case MesgNum.HRV:
            return new HrvMesg(mesg);       
         case MesgNum.COURSE:
            return new CourseMesg(mesg);       
         case MesgNum.COURSE_POINT:
            return new CoursePointMesg(mesg);       
         case MesgNum.WORKOUT:
            return new WorkoutMesg(mesg);       
         case MesgNum.WORKOUT_STEP:
            return new WorkoutStepMesg(mesg);       
         case MesgNum.TOTALS:
            return new TotalsMesg(mesg);       
         case MesgNum.WEIGHT_SCALE:
            return new WeightScaleMesg(mesg);       
         case MesgNum.BLOOD_PRESSURE:
            return new BloodPressureMesg(mesg);
         default:
            break;
      }
      return new Mesg("unknown", MesgNum.INVALID);
   }

   static public Mesg createMesg(int mesgNum) {
      for (int i = 0; i < mesgs.length; i++) {
         if (mesgs[i].num == mesgNum)
            return new Mesg(mesgs[i]);
      }
      return new Mesg("unknown", mesgNum);
   }

   static public Mesg createMesg(String mesgName) {
      for (int i = 0; i < mesgs.length; i++) {
         if (mesgs[i].name.equals(mesgName))
            return new Mesg(mesgs[i]);
      }
      return new Mesg(mesgName, MesgNum.INVALID);
   }

   static public Field createField(String mesgName, String fieldName) {
      for (int i = 0; i < mesgs.length; i++) {
         if (mesgs[i].name.equals(mesgName)) {
            return new Field(mesgs[i].getField(fieldName, false));
         }
      }
      return new Field(fieldName, Fit.FIELD_NUM_INVALID, 0, 1, 0, "");
   }

   static public Field createField(String mesgName, int fieldNum) {
      for (int i = 0; i < mesgs.length; i++) {
         if (mesgs[i].name.equals(mesgName)) {
            return new Field(mesgs[i].getField(fieldNum));
         }
      }
      return new Field("unknown", fieldNum, 0, 1, 0, "");
   }

   static public Field createField(int mesgNum, int fieldNum) {
      for (int i = 0; i < mesgs.length; i++) {
         if (mesgs[i].num == mesgNum) {
            return new Field(mesgs[i].getField(fieldNum));
         }
      }
      return new Field("unknown", fieldNum, 0, 1, 0, "");
   }

   static public Field createField(int mesgNum, String fieldName) {
      for (int i = 0; i < mesgs.length; i++) {
         if (mesgs[i].num == mesgNum) {
            return new Field(mesgs[i].getField(fieldName, false));
         }
      }
      return new Field(fieldName, Fit.FIELD_NUM_INVALID, 0, 1, 0, "");
   }

   static public Field createField(String mesgName, String fieldName, ArrayList<Object> values) {
      Field field = createField(mesgName, fieldName);
      field.values = values;
      return field;
   }

   private static final Mesg mesgs[] = new Mesg[33];

   static {
      int mesg_index = 0;
      int field_index;
      int subfield_index;

      // file_id
      field_index = 0;
      mesgs[mesg_index] = new Mesg("file_id", MesgNum.FILE_ID);
      mesgs[mesg_index].addField(new Field("type", 0, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("manufacturer", 1, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("product", 2, 132, 1, 0, ""));
      subfield_index = 0;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("garmin_product", 132, 1, 0, ""));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(1, 1);
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(1, 15);
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(1, 13);
      subfield_index++;
      field_index++;
      mesgs[mesg_index].addField(new Field("serial_number", 3, 140, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("time_created", 4, 134, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("number", 5, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("checksum", 252, 2, 1, 0, ""));
      field_index++;
      mesg_index++;

      // file_creator
      field_index = 0;
      mesgs[mesg_index] = new Mesg("file_creator", MesgNum.FILE_CREATOR);
      mesgs[mesg_index].addField(new Field("software_version", 0, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("hardware_version", 1, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("checksum", 252, 2, 1, 0, ""));
      field_index++;
      mesg_index++;

      // pad
      field_index = 0;
      mesgs[mesg_index] = new Mesg("pad", MesgNum.PAD);
      mesgs[mesg_index].addField(new Field("pad", 0, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("checksum", 252, 2, 1, 0, ""));
      field_index++;
      mesg_index++;

      // software
      field_index = 0;
      mesgs[mesg_index] = new Mesg("software", MesgNum.SOFTWARE);
      mesgs[mesg_index].addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("version", 3, 132, 100, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("part_number", 5, 7, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("checksum", 252, 2, 1, 0, ""));
      field_index++;
      mesg_index++;

      // capabilities
      field_index = 0;
      mesgs[mesg_index] = new Mesg("capabilities", MesgNum.CAPABILITIES);
      mesgs[mesg_index].addField(new Field("languages", 0, 10, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("sports", 1, 10, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("workouts_supported", 21, 140, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("checksum", 252, 2, 1, 0, ""));
      field_index++;
      mesg_index++;

      // file_capabilities
      field_index = 0;
      mesgs[mesg_index] = new Mesg("file_capabilities", MesgNum.FILE_CAPABILITIES);
      mesgs[mesg_index].addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("type", 0, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("flags", 1, 10, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("directory", 2, 7, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("max_count", 3, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("max_size", 4, 134, 1, 0, "bytes"));
      field_index++;
      mesgs[mesg_index].addField(new Field("checksum", 252, 2, 1, 0, ""));
      field_index++;
      mesg_index++;

      // mesg_capabilities
      field_index = 0;
      mesgs[mesg_index] = new Mesg("mesg_capabilities", MesgNum.MESG_CAPABILITIES);
      mesgs[mesg_index].addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("file", 0, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("mesg_num", 1, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("count_type", 2, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("count", 3, 132, 1, 0, ""));
      subfield_index = 0;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("num_per_file", 132, 1, 0, ""));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(2, 0);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("max_per_file", 132, 1, 0, ""));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(2, 1);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("max_per_file_type", 132, 1, 0, ""));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(2, 2);
      subfield_index++;
      field_index++;
      mesgs[mesg_index].addField(new Field("checksum", 252, 2, 1, 0, ""));
      field_index++;
      mesg_index++;

      // field_capabilities
      field_index = 0;
      mesgs[mesg_index] = new Mesg("field_capabilities", MesgNum.FIELD_CAPABILITIES);
      mesgs[mesg_index].addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("file", 0, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("mesg_num", 1, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("field_num", 2, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("count", 3, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("checksum", 252, 2, 1, 0, ""));
      field_index++;
      mesg_index++;

      // device_settings
      field_index = 0;
      mesgs[mesg_index] = new Mesg("device_settings", MesgNum.DEVICE_SETTINGS);
      mesgs[mesg_index].addField(new Field("utc_offset", 1, 134, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("checksum", 252, 2, 1, 0, ""));
      field_index++;
      mesg_index++;

      // user_profile
      field_index = 0;
      mesgs[mesg_index] = new Mesg("user_profile", MesgNum.USER_PROFILE);
      mesgs[mesg_index].addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("friendly_name", 0, 7, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("gender", 1, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("age", 2, 2, 1, 0, "years"));
      field_index++;
      mesgs[mesg_index].addField(new Field("height", 3, 2, 100, 0, "m"));
      field_index++;
      mesgs[mesg_index].addField(new Field("weight", 4, 132, 10, 0, "kg"));
      field_index++;
      mesgs[mesg_index].addField(new Field("language", 5, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("elev_setting", 6, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("weight_setting", 7, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("resting_heart_rate", 8, 2, 1, 0, "bpm"));
      field_index++;
      mesgs[mesg_index].addField(new Field("default_max_running_heart_rate", 9, 2, 1, 0, "bpm"));
      field_index++;
      mesgs[mesg_index].addField(new Field("default_max_biking_heart_rate", 10, 2, 1, 0, "bpm"));
      field_index++;
      mesgs[mesg_index].addField(new Field("default_max_heart_rate", 11, 2, 1, 0, "bpm"));
      field_index++;
      mesgs[mesg_index].addField(new Field("hr_setting", 12, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("speed_setting", 13, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("dist_setting", 14, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("power_setting", 16, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("activity_class", 17, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("position_setting", 18, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("temperature_setting", 21, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("local_id", 22, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("global_id", 23, 13, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("checksum", 252, 2, 1, 0, ""));
      field_index++;
      mesg_index++;

      // hrm_profile
      field_index = 0;
      mesgs[mesg_index] = new Mesg("hrm_profile", MesgNum.HRM_PROFILE);
      mesgs[mesg_index].addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("enabled", 0, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("hrm_ant_id", 1, 139, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("log_hrv", 2, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("hrm_ant_id_trans_type", 3, 10, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("checksum", 252, 2, 1, 0, ""));
      field_index++;
      mesg_index++;

      // sdm_profile
      field_index = 0;
      mesgs[mesg_index] = new Mesg("sdm_profile", MesgNum.SDM_PROFILE);
      mesgs[mesg_index].addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("enabled", 0, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("sdm_ant_id", 1, 139, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("sdm_cal_factor", 2, 132, 10, 0, "%"));
      field_index++;
      mesgs[mesg_index].addField(new Field("odometer", 3, 134, 100, 0, "m"));
      field_index++;
      mesgs[mesg_index].addField(new Field("speed_source", 4, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("sdm_ant_id_trans_type", 5, 10, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("checksum", 252, 2, 1, 0, ""));
      field_index++;
      mesg_index++;

      // bike_profile
      field_index = 0;
      mesgs[mesg_index] = new Mesg("bike_profile", MesgNum.BIKE_PROFILE);
      mesgs[mesg_index].addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("name", 0, 7, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("sport", 1, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("sub_sport", 2, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("odometer", 3, 134, 100, 0, "m"));
      field_index++;
      mesgs[mesg_index].addField(new Field("bike_spd_ant_id", 4, 139, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("bike_cad_ant_id", 5, 139, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("bike_spdcad_ant_id", 6, 139, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("bike_power_ant_id", 7, 139, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("custom_wheelsize", 8, 132, 1000, 0, "m"));
      field_index++;
      mesgs[mesg_index].addField(new Field("auto_wheelsize", 9, 132, 1000, 0, "m"));
      field_index++;
      mesgs[mesg_index].addField(new Field("bike_weight", 10, 132, 10, 0, "kg"));
      field_index++;
      mesgs[mesg_index].addField(new Field("power_cal_factor", 11, 132, 10, 0, "%"));
      field_index++;
      mesgs[mesg_index].addField(new Field("auto_wheel_cal", 12, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("auto_power_zero", 13, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("id", 14, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("spd_enabled", 15, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("cad_enabled", 16, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("spdcad_enabled", 17, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("power_enabled", 18, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("crank_length", 19, 2, 2, -110, "mm"));
      field_index++;
      mesgs[mesg_index].addField(new Field("enabled", 20, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("bike_spd_ant_id_trans_type", 21, 10, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("bike_cad_ant_id_trans_type", 22, 10, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("bike_spdcad_ant_id_trans_type", 23, 10, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("bike_power_ant_id_trans_type", 24, 10, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("checksum", 252, 2, 1, 0, ""));
      field_index++;
      mesg_index++;

      // zones_target
      field_index = 0;
      mesgs[mesg_index] = new Mesg("zones_target", MesgNum.ZONES_TARGET);
      mesgs[mesg_index].addField(new Field("max_heart_rate", 1, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("threshold_heart_rate", 2, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("functional_threshold_power", 3, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("hr_calc_type", 5, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("pwr_calc_type", 7, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("checksum", 252, 2, 1, 0, ""));
      field_index++;
      mesg_index++;

      // sport
      field_index = 0;
      mesgs[mesg_index] = new Mesg("sport", MesgNum.SPORT);
      mesgs[mesg_index].addField(new Field("sport", 0, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("sub_sport", 1, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("name", 3, 7, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("checksum", 252, 2, 1, 0, ""));
      field_index++;
      mesg_index++;

      // hr_zone
      field_index = 0;
      mesgs[mesg_index] = new Mesg("hr_zone", MesgNum.HR_ZONE);
      mesgs[mesg_index].addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("high_bpm", 1, 2, 1, 0, "bpm"));
      field_index++;
      mesgs[mesg_index].addField(new Field("name", 2, 7, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("checksum", 252, 2, 1, 0, ""));
      field_index++;
      mesg_index++;

      // power_zone
      field_index = 0;
      mesgs[mesg_index] = new Mesg("power_zone", MesgNum.POWER_ZONE);
      mesgs[mesg_index].addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("high_value", 1, 132, 1, 0, "watts"));
      field_index++;
      mesgs[mesg_index].addField(new Field("name", 2, 7, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("checksum", 252, 2, 1, 0, ""));
      field_index++;
      mesg_index++;

      // met_zone
      field_index = 0;
      mesgs[mesg_index] = new Mesg("met_zone", MesgNum.MET_ZONE);
      mesgs[mesg_index].addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("high_bpm", 1, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("calories", 2, 132, 10, 0, "kcal / min"));
      field_index++;
      mesgs[mesg_index].addField(new Field("fat_calories", 3, 2, 10, 0, "kcal / min"));
      field_index++;
      mesgs[mesg_index].addField(new Field("checksum", 252, 2, 1, 0, ""));
      field_index++;
      mesg_index++;

      // goal
      field_index = 0;
      mesgs[mesg_index] = new Mesg("goal", MesgNum.GOAL);
      mesgs[mesg_index].addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("sport", 0, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("sub_sport", 1, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("start_date", 2, 134, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("end_date", 3, 134, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("type", 4, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("value", 5, 134, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("repeat", 6, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("target_value", 7, 134, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("recurrence", 8, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("recurrence_value", 9, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("enabled", 10, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("checksum", 252, 2, 1, 0, ""));
      field_index++;
      mesg_index++;

      // activity
      field_index = 0;
      mesgs[mesg_index] = new Mesg("activity", MesgNum.ACTIVITY);
      mesgs[mesg_index].addField(new Field("timestamp", 253, 134, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_timer_time", 0, 134, 1000, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("num_sessions", 1, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("type", 2, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("event", 3, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("event_type", 4, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("local_timestamp", 5, 134, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("event_group", 6, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("checksum", 252, 2, 1, 0, ""));
      field_index++;
      mesg_index++;

      // session
      field_index = 0;
      mesgs[mesg_index] = new Mesg("session", MesgNum.SESSION);
      mesgs[mesg_index].addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("timestamp", 253, 134, 1, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("event", 0, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("event_type", 1, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("start_time", 2, 134, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("start_position_lat", 3, 133, 1, 0, "semicircles"));
      field_index++;
      mesgs[mesg_index].addField(new Field("start_position_long", 4, 133, 1, 0, "semicircles"));
      field_index++;
      mesgs[mesg_index].addField(new Field("sport", 5, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("sub_sport", 6, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_elapsed_time", 7, 134, 1000, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_timer_time", 8, 134, 1000, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_distance", 9, 134, 100, 0, "m"));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_cycles", 10, 134, 1, 0, "cycles"));
      subfield_index = 0;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("total_strides", 134, 1, 0, "strides"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(5, 1);
      subfield_index++;
      field_index++;
      mesgs[mesg_index].addField(new Field("total_calories", 11, 132, 1, 0, "kcal"));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_fat_calories", 13, 132, 1, 0, "kcal"));
      field_index++;
      mesgs[mesg_index].addField(new Field("avg_speed", 14, 132, 1000, 0, "m/s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("max_speed", 15, 132, 1000, 0, "m/s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("avg_heart_rate", 16, 2, 1, 0, "bpm"));
      field_index++;
      mesgs[mesg_index].addField(new Field("max_heart_rate", 17, 2, 1, 0, "bpm"));
      field_index++;
      mesgs[mesg_index].addField(new Field("avg_cadence", 18, 2, 1, 0, "rpm"));
      subfield_index = 0;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("avg_running_cadence", 2, 1, 0, "strides/min"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(5, 1);
      subfield_index++;
      field_index++;
      mesgs[mesg_index].addField(new Field("max_cadence", 19, 2, 1, 0, "rpm"));
      subfield_index = 0;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("max_running_cadence", 2, 1, 0, "strides/min"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(5, 1);
      subfield_index++;
      field_index++;
      mesgs[mesg_index].addField(new Field("avg_power", 20, 132, 1, 0, "watts"));
      field_index++;
      mesgs[mesg_index].addField(new Field("max_power", 21, 132, 1, 0, "watts"));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_ascent", 22, 132, 1, 0, "m"));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_descent", 23, 132, 1, 0, "m"));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_training_effect", 24, 2, 10, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("first_lap_index", 25, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("num_laps", 26, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("event_group", 27, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("trigger", 28, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("nec_lat", 29, 133, 1, 0, "semicircles"));
      field_index++;
      mesgs[mesg_index].addField(new Field("nec_long", 30, 133, 1, 0, "semicircles"));
      field_index++;
      mesgs[mesg_index].addField(new Field("swc_lat", 31, 133, 1, 0, "semicircles"));
      field_index++;
      mesgs[mesg_index].addField(new Field("swc_long", 32, 133, 1, 0, "semicircles"));
      field_index++;
      mesgs[mesg_index].addField(new Field("normalized_power", 34, 132, 1, 0, "watts"));
      field_index++;
      mesgs[mesg_index].addField(new Field("training_stress_score", 35, 132, 10, 0, "tss"));
      field_index++;
      mesgs[mesg_index].addField(new Field("intensity_factor", 36, 132, 1000, 0, "if"));
      field_index++;
      mesgs[mesg_index].addField(new Field("left_right_balance", 37, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("checksum", 252, 2, 1, 0, ""));
      field_index++;
      mesg_index++;

      // lap
      field_index = 0;
      mesgs[mesg_index] = new Mesg("lap", MesgNum.LAP);
      mesgs[mesg_index].addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("timestamp", 253, 134, 1, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("event", 0, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("event_type", 1, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("start_time", 2, 134, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("start_position_lat", 3, 133, 1, 0, "semicircles"));
      field_index++;
      mesgs[mesg_index].addField(new Field("start_position_long", 4, 133, 1, 0, "semicircles"));
      field_index++;
      mesgs[mesg_index].addField(new Field("end_position_lat", 5, 133, 1, 0, "semicircles"));
      field_index++;
      mesgs[mesg_index].addField(new Field("end_position_long", 6, 133, 1, 0, "semicircles"));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_elapsed_time", 7, 134, 1000, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_timer_time", 8, 134, 1000, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_distance", 9, 134, 100, 0, "m"));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_cycles", 10, 134, 1, 0, "cycles"));
      subfield_index = 0;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("total_strides", 134, 1, 0, "strides"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(25, 1);
      subfield_index++;
      field_index++;
      mesgs[mesg_index].addField(new Field("total_calories", 11, 132, 1, 0, "kcal"));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_fat_calories", 12, 132, 1, 0, "kcal"));
      field_index++;
      mesgs[mesg_index].addField(new Field("avg_speed", 13, 132, 1000, 0, "m/s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("max_speed", 14, 132, 1000, 0, "m/s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("avg_heart_rate", 15, 2, 1, 0, "bpm"));
      field_index++;
      mesgs[mesg_index].addField(new Field("max_heart_rate", 16, 2, 1, 0, "bpm"));
      field_index++;
      mesgs[mesg_index].addField(new Field("avg_cadence", 17, 2, 1, 0, "rpm"));
      subfield_index = 0;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("avg_running_cadence", 2, 1, 0, "strides/min"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(25, 1);
      subfield_index++;
      field_index++;
      mesgs[mesg_index].addField(new Field("max_cadence", 18, 2, 1, 0, "rpm"));
      subfield_index = 0;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("max_running_cadence", 2, 1, 0, "strides/min"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(25, 1);
      subfield_index++;
      field_index++;
      mesgs[mesg_index].addField(new Field("avg_power", 19, 132, 1, 0, "watts"));
      field_index++;
      mesgs[mesg_index].addField(new Field("max_power", 20, 132, 1, 0, "watts"));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_ascent", 21, 132, 1, 0, "m"));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_descent", 22, 132, 1, 0, "m"));
      field_index++;
      mesgs[mesg_index].addField(new Field("intensity", 23, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("lap_trigger", 24, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("sport", 25, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("event_group", 26, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("normalized_power", 33, 132, 1, 0, "watts"));
      field_index++;
      mesgs[mesg_index].addField(new Field("left_right_balance", 34, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("checksum", 252, 2, 1, 0, ""));
      field_index++;
      mesg_index++;

      // record
      field_index = 0;
      mesgs[mesg_index] = new Mesg("record", MesgNum.RECORD);
      mesgs[mesg_index].addField(new Field("timestamp", 253, 134, 1, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("position_lat", 0, 133, 1, 0, "semicircles"));
      field_index++;
      mesgs[mesg_index].addField(new Field("position_long", 1, 133, 1, 0, "semicircles"));
      field_index++;
      mesgs[mesg_index].addField(new Field("altitude", 2, 132, 5, 500, "m"));
      field_index++;
      mesgs[mesg_index].addField(new Field("heart_rate", 3, 2, 1, 0, "bpm"));
      field_index++;
      mesgs[mesg_index].addField(new Field("cadence", 4, 2, 1, 0, "rpm"));
      field_index++;
      mesgs[mesg_index].addField(new Field("distance", 5, 134, 100, 0, "m"));
      field_index++;
      mesgs[mesg_index].addField(new Field("speed", 6, 132, 1000, 0, "m/s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("power", 7, 132, 1, 0, "watts"));
      field_index++;
      mesgs[mesg_index].addField(new Field("compressed_speed_distance", 8, 13, 1, 0, "")); 
      mesgs[mesg_index].fields.get(field_index).components.add(new FieldComponent(6, false, 12, 100, 0)); // speed 
      mesgs[mesg_index].fields.get(field_index).components.add(new FieldComponent(5, true, 12, 16, 0)); // distance
      field_index++;
      mesgs[mesg_index].addField(new Field("grade", 9, 131, 100, 0, "%"));
      field_index++;
      mesgs[mesg_index].addField(new Field("resistance", 10, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("time_from_course", 11, 133, 1000, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("cycle_length", 12, 2, 100, 0, "m"));
      field_index++;
      mesgs[mesg_index].addField(new Field("temperature", 13, 1, 1, 0, "C"));
      field_index++;
      mesgs[mesg_index].addField(new Field("speed_1s", 17, 2, 16, 0, "m/s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("cycles", 18, 2, 1, 0, "")); 
      mesgs[mesg_index].fields.get(field_index).components.add(new FieldComponent(19, true, 8, 1, 0)); // total_cycles
      field_index++;
      mesgs[mesg_index].addField(new Field("total_cycles", 19, 134, 1, 0, "cycles"));
      field_index++;
      mesgs[mesg_index].addField(new Field("compressed_accumulated_power", 28, 132, 1, 0, "")); 
      mesgs[mesg_index].fields.get(field_index).components.add(new FieldComponent(29, true, 16, 1, 0)); // accumulated_power
      field_index++;
      mesgs[mesg_index].addField(new Field("accumulated_power", 29, 134, 1, 0, "watts"));
      field_index++;
      mesgs[mesg_index].addField(new Field("left_right_balance", 30, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("checksum", 252, 2, 1, 0, ""));
      field_index++;
      mesg_index++;

      // event
      field_index = 0;
      mesgs[mesg_index] = new Mesg("event", MesgNum.EVENT);
      mesgs[mesg_index].addField(new Field("timestamp", 253, 134, 1, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("event", 0, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("event_type", 1, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("data16", 2, 132, 1, 0, "")); 
      mesgs[mesg_index].fields.get(field_index).components.add(new FieldComponent(3, false, 16, 1, 0)); // data
      field_index++;
      mesgs[mesg_index].addField(new Field("data", 3, 134, 1, 0, ""));
      subfield_index = 0;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("timer_trigger", 0, 1, 0, ""));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(0, 0);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("course_point_index", 132, 1, 0, ""));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(0, 10);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("battery_level", 132, 1000, 0, "V"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(0, 11);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("virtual_partner_speed", 132, 1000, 0, "m/s"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(0, 12);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("hr_high_alert", 2, 1, 0, "bpm"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(0, 13);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("hr_low_alert", 2, 1, 0, "bpm"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(0, 14);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("speed_high_alert", 132, 1000, 0, "m/s"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(0, 15);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("speed_low_alert", 132, 1000, 0, "m/s"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(0, 16);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("cad_high_alert", 132, 1, 0, "rpm"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(0, 17);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("cad_low_alert", 132, 1, 0, "rpm"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(0, 18);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("power_high_alert", 132, 1, 0, "watts"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(0, 19);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("power_low_alert", 132, 1, 0, "watts"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(0, 20);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("time_duration_alert", 134, 1000, 0, "s"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(0, 23);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("distance_duration_alert", 134, 100, 0, "m"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(0, 24);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("calorie_duration_alert", 134, 1, 0, "calories"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(0, 25);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("fitness_equipment_state", 0, 1, 0, ""));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(0, 27);
      subfield_index++;
      field_index++;
      mesgs[mesg_index].addField(new Field("event_group", 4, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("checksum", 252, 2, 1, 0, ""));
      field_index++;
      mesg_index++;

      // device_info
      field_index = 0;
      mesgs[mesg_index] = new Mesg("device_info", MesgNum.DEVICE_INFO);
      mesgs[mesg_index].addField(new Field("timestamp", 253, 134, 1, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("device_index", 0, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("device_type", 1, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("manufacturer", 2, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("serial_number", 3, 140, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("product", 4, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("software_version", 5, 132, 100, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("hardware_version", 6, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("cum_operating_time", 7, 134, 1, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("battery_voltage", 10, 132, 256, 0, "V"));
      field_index++;
      mesgs[mesg_index].addField(new Field("battery_status", 11, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("checksum", 252, 2, 1, 0, ""));
      field_index++;
      mesg_index++;

      // hrv
      field_index = 0;
      mesgs[mesg_index] = new Mesg("hrv", MesgNum.HRV);
      mesgs[mesg_index].addField(new Field("time", 0, 132, 1000, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("checksum", 252, 2, 1, 0, ""));
      field_index++;
      mesg_index++;

      // course
      field_index = 0;
      mesgs[mesg_index] = new Mesg("course", MesgNum.COURSE);
      mesgs[mesg_index].addField(new Field("sport", 4, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("name", 5, 7, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("capabilities", 6, 140, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("checksum", 252, 2, 1, 0, ""));
      field_index++;
      mesg_index++;

      // course_point
      field_index = 0;
      mesgs[mesg_index] = new Mesg("course_point", MesgNum.COURSE_POINT);
      mesgs[mesg_index].addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("timestamp", 1, 134, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("position_lat", 2, 133, 1, 0, "semicircles"));
      field_index++;
      mesgs[mesg_index].addField(new Field("position_long", 3, 133, 1, 0, "semicircles"));
      field_index++;
      mesgs[mesg_index].addField(new Field("distance", 4, 134, 100, 0, "m"));
      field_index++;
      mesgs[mesg_index].addField(new Field("type", 5, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("name", 6, 7, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("checksum", 252, 2, 1, 0, ""));
      field_index++;
      mesg_index++;

      // workout
      field_index = 0;
      mesgs[mesg_index] = new Mesg("workout", MesgNum.WORKOUT);
      mesgs[mesg_index].addField(new Field("sport", 4, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("capabilities", 5, 140, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("num_valid_steps", 6, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("wkt_name", 8, 7, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("checksum", 252, 2, 1, 0, ""));
      field_index++;
      mesg_index++;

      // workout_step
      field_index = 0;
      mesgs[mesg_index] = new Mesg("workout_step", MesgNum.WORKOUT_STEP);
      mesgs[mesg_index].addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("wkt_step_name", 0, 7, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("duration_type", 1, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("duration_value", 2, 134, 1, 0, ""));
      subfield_index = 0;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("duration_time", 134, 1000, 0, "s"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(1, 0);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("duration_distance", 134, 100, 0, "m"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(1, 1);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("duration_hr", 134, 1, 0, "% or bpm"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(1, 2);
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(1, 3);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("duration_calories", 134, 1, 0, "calories"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(1, 4);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("duration_step", 134, 1, 0, ""));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(1, 6);
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(1, 7);
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(1, 8);
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(1, 9);
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(1, 10);
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(1, 11);
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(1, 12);
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(1, 13);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("duration_power", 134, 1, 0, "% or watts"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(1, 14);
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(1, 15);
      subfield_index++;
      field_index++;
      mesgs[mesg_index].addField(new Field("target_type", 3, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("target_value", 4, 134, 1, 0, ""));
      subfield_index = 0;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("target_hr_zone", 134, 1, 0, ""));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(3, 1);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("target_power_zone", 134, 1, 0, ""));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(3, 4);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("repeat_steps", 134, 1, 0, ""));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(1, 6);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("repeat_time", 134, 1000, 0, "s"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(1, 7);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("repeat_distance", 134, 100, 0, "m"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(1, 8);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("repeat_calories", 134, 1, 0, "calories"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(1, 9);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("repeat_hr", 134, 1, 0, "% or bpm"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(1, 10);
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(1, 11);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("repeat_power", 134, 1, 0, "% or watts"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(1, 12);
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(1, 13);
      subfield_index++;
      field_index++;
      mesgs[mesg_index].addField(new Field("custom_target_value_low", 5, 134, 1, 0, ""));
      subfield_index = 0;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("custom_target_speed_low", 134, 1000, 0, "m/s"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(3, 0);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("custom_target_heart_rate_low", 134, 1, 0, "% or bpm"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(3, 1);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("custom_target_cadence_low", 134, 1, 0, "rpm"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(3, 3);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("custom_target_power_low", 134, 1, 0, "% or watts"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(3, 4);
      subfield_index++;
      field_index++;
      mesgs[mesg_index].addField(new Field("custom_target_value_high", 6, 134, 1, 0, ""));
      subfield_index = 0;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("custom_target_speed_high", 134, 1000, 0, "m/s"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(3, 0);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("custom_target_heart_rate_high", 134, 1, 0, "% or bpm"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(3, 1);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("custom_target_cadence_high", 134, 1, 0, "rpm"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(3, 3);
      subfield_index++;
      mesgs[mesg_index].fields.get(field_index).subFields.add(new SubField("custom_target_power_high", 134, 1, 0, "% or watts"));
      mesgs[mesg_index].fields.get(field_index).subFields.get(subfield_index).addMap(3, 4);
      subfield_index++;
      field_index++;
      mesgs[mesg_index].addField(new Field("intensity", 7, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("checksum", 252, 2, 1, 0, ""));
      field_index++;
      mesg_index++;

      // totals
      field_index = 0;
      mesgs[mesg_index] = new Mesg("totals", MesgNum.TOTALS);
      mesgs[mesg_index].addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("timestamp", 253, 134, 1, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("timer_time", 0, 134, 1, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("distance", 1, 134, 1, 0, "m"));
      field_index++;
      mesgs[mesg_index].addField(new Field("calories", 2, 134, 1, 0, "kcal"));
      field_index++;
      mesgs[mesg_index].addField(new Field("sport", 3, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("elapsed_time", 4, 134, 1, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("sessions", 5, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("checksum", 252, 2, 1, 0, ""));
      field_index++;
      mesg_index++;

      // weight_scale
      field_index = 0;
      mesgs[mesg_index] = new Mesg("weight_scale", MesgNum.WEIGHT_SCALE);
      mesgs[mesg_index].addField(new Field("timestamp", 253, 134, 1, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("weight", 0, 132, 100, 0, "kg"));
      field_index++;
      mesgs[mesg_index].addField(new Field("percent_fat", 1, 132, 100, 0, "%"));
      field_index++;
      mesgs[mesg_index].addField(new Field("percent_hydration", 2, 132, 100, 0, "%"));
      field_index++;
      mesgs[mesg_index].addField(new Field("visceral_fat_mass", 3, 132, 100, 0, "kg"));
      field_index++;
      mesgs[mesg_index].addField(new Field("bone_mass", 4, 132, 100, 0, "kg"));
      field_index++;
      mesgs[mesg_index].addField(new Field("muscle_mass", 5, 132, 100, 0, "kg"));
      field_index++;
      mesgs[mesg_index].addField(new Field("basal_met", 7, 132, 4, 0, "kcal/day"));
      field_index++;
      mesgs[mesg_index].addField(new Field("physique_rating", 8, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("active_met", 9, 132, 4, 0, "kcal/day"));
      field_index++;
      mesgs[mesg_index].addField(new Field("metabolic_age", 10, 2, 1, 0, "years"));
      field_index++;
      mesgs[mesg_index].addField(new Field("visceral_fat_rating", 11, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("user_profile_index", 12, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("checksum", 252, 2, 1, 0, ""));
      field_index++;
      mesg_index++;

      // blood_pressure
      field_index = 0;
      mesgs[mesg_index] = new Mesg("blood_pressure", MesgNum.BLOOD_PRESSURE);
      mesgs[mesg_index].addField(new Field("timestamp", 253, 134, 1, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("systolic_pressure", 0, 132, 1, 0, "mmHg"));
      field_index++;
      mesgs[mesg_index].addField(new Field("diastolic_pressure", 1, 132, 1, 0, "mmHg"));
      field_index++;
      mesgs[mesg_index].addField(new Field("mean_arterial_pressure", 2, 132, 1, 0, "mmHg"));
      field_index++;
      mesgs[mesg_index].addField(new Field("map_3_sample_mean", 3, 132, 1, 0, "mmHg"));
      field_index++;
      mesgs[mesg_index].addField(new Field("map_morning_values", 4, 132, 1, 0, "mmHg"));
      field_index++;
      mesgs[mesg_index].addField(new Field("map_evening_values", 5, 132, 1, 0, "mmHg"));
      field_index++;
      mesgs[mesg_index].addField(new Field("heart_rate", 6, 2, 1, 0, "bpm"));
      field_index++;
      mesgs[mesg_index].addField(new Field("heart_rate_type", 7, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("status", 8, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("user_profile_index", 9, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("checksum", 252, 2, 1, 0, ""));
      field_index++;
      mesg_index++;

   }
}
