require('trainings/views/application');
require('trainings/views/activity');
require('trainings/views/activities');
require('trainings/views/activity-list');
require('trainings/views/dashboard');
require('trainings/views/equipments');
require('trainings/views/overview-graph');
require('trainings/views/nav');
require('trainings/views/sport-summary');
